### ISSUE TITLE
Ruby 1.9: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Stanley** [davetroy/geohash#1]
Hi,
trying to install gem on ruby 1.9, I got the following error:

Building native extensions.  This could take a while...
ERROR:  Error installing davetroy-geohash:
    ERROR: Failed to build gem native extension.

/usr/local/bin/ruby extconf.rb
creating Makefile

make
gcc -I. -I/usr/local/include/ruby-1.9.1/x86_64-linux -I/usr/local/include/ruby-1.9.1/ruby/backward -I/usr/local/include/ruby-1.9.1 -I.   -fPIC  -O2 -g -Wall -Wno-parentheses  -o geohash_native.o -c geohash_native.c
geohash_native.c: In function ‘encode’:
geohash_native.c:123: error: ‘struct RFloat’ has no member named ‘value’
geohash_native.c:123: error: ‘struct RFloat’ has no member named ‘value’
geohash_native.c: In function ‘decode_bbox’:
geohash_native.c:135: error: ‘struct RString’ has no member named ‘ptr’
geohash_native.c: In function ‘decode’:
geohash_native.c:158: error: ‘struct RString’ has no member named ‘ptr’
geohash_native.c: In function ‘calculate_adjacent’:
geohash_native.c:196: error: ‘struct RString’ has no member named ‘ptr’
geohash_native.c:199: error: ‘struct RString’ has no member named ‘ptr’
make: **\* [geohash_native.o] Błąd 1

Gem files will remain installed in /usr/local/lib/ruby/gems/1.9.1/gems/davetroy-geohash-1.1.0 for inspection.
Results logged to /usr/local/lib/ruby/gems/1.9.1/gems/davetroy-geohash-1.1.0/ext/gem_make.out

**Comment by bilow-factual** [comment]
c_geohash works on ruby 2.2.0 as well.
